name: uarray
channels:
  - pytorch
  - xnd/label/dev
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-cov
  - mypy
  - pytorch-cpu
  - scipy
  - gumath
  - dask
  - sparse
  - doc8
  - black
  - pip:
    - pytest-mypy
    - pytest-black
