name: uarray
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pytest-cov
  - mypy
  - doc8
  - black
  - pip:
    - pytest-mypy
    - pytest-black
